### ISSUE TITLE
Publish releases and switch projects over to using this as a dependency

### ISSUE THREAD

**Issue by lmorchard** [mozilla-fxa/storybook-gcp-publisher#2]
Currently, two projects run this code directly from github latest main branch via `npx`:

* [mozilla/experimenter](https://github.com/mozilla/experimenter/blob/main/Makefile#L47)
* [mozilla/fxa](https://github.com/mozilla/fxa/blob/main/.circleci/config.yml#L281)

A better situation would be to shift over to releases published to NPM, then specify versions in respective projects' `package.json` files. Then, changes here would be less likely to surprisingly break those other projects.

**Comment by StaberindeZA** [comment]
Just wanted to note that it looks like `mozilla/experimenter` no longer use this code, as of [PR 7198](https://github.com/mozilla/experimenter/pull/7198/files).

`mozilla/fxa` still uses this code.

**Comment by clouserw** [comment]
I noticed storybook recommends using https://www.chromatic.com/ which is free for open source.  Maybe we should investigate that instead of maintaining this library.  Another option is a github action -- looks like there are existing options there too, e.g. https://github.com/bitovi/github-actions-storybook-to-github-pages

**Comment by lmorchard** [comment]
It's been a few years since I touched this stuff myself. So, I'd agree it's probably worth moving away from this and doing something simpler. The stuff that this storybook-gcp-publisher is doing to build a navigable static web site in Google Cloud probably turns out not to be as handy as just dumping stuff onto Github Pages and linking from PRs

FWIW, we're using Storybook over on Didthis in the mozilla-ocho org with just a couple github actions. I think the part that used to be tricky - i.e. posting Status Checks to PRs - has since become doable just within an action workflow gluing a few things together. 

I blogged about how we're doing Storybook on Didthis, over here, for reference:

https://blog.lmorchard.com/2024/03/13/github-actions-for-didthis/

You might be able to get some mileage out of something like this workflow in particular:

```yaml
name: "Build & Deploy Storybook"
on:
  push:
    branches:
      - 'main'
      - 'preview/**'
permissions:
  contents: write
  checks: write
  pages: write
  statuses: write
jobs:
  storybook:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: appserver
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "yarn"
          cache-dependency-path: "appserver/yarn.lock"
      - name: Install Dependencies
        run: yarn install
      - name: Build Storybook
        run: yarn build-storybook
      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: appserver/storybook-static
          target-folder: storybooks/${{ github.head_ref || github.ref_name }}/
      - name: Get Github Pages Base URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          githubPagesUrl="$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')"
          echo 'GITHUB_PAGES_URL='$githubPagesUrl >> $GITHUB_ENV
      - name: Create Status Check
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha || github.sha }}
          state: 'success'
          context: 'Storybook Deployment'
          description: 'Storybook Deployment for ${{ github.head_ref || github.ref_name }}'
          target_url: '${{ env.GITHUB_PAGES_URL }}storybooks/${{ github.head_ref || github.ref_name }}/index.html'
```
